### PR TITLE
fix: use readble models name 

### LINKED ISSUE #100: Use readable models name
Just like on the models page. We can also use readable models names on playground.

### PR DESCRIPTION
**Pull request by fishonamos**
closes #100

### CODE REVIEW

File: utils/utils.ts [hunk 1]
```diff
@@ -15,11 +15,33 @@ export async function fetchAvailableModels(): Promise<TaskResponse> {
...
 
+export function readableModelName(modelName: string) {
+  switch (modelName) {
+    case "Qwen/QwQ-32B":
+      return "QWQ 32B";
+    case "neuralmagic/DeepSeek-R1-Distill-Llama-70B-FP8-dynamic":
+      return "DeepSeek: R1 Distill Llama 70B";
+    case "neuralmagic/Qwen2-72B-Instruct-FP8":
+      return "Qwen2 72B";
+    case "meta-llama/Llama-3.1-8B-Instruct":
```
Comment (jorgeantonio21) [inline utils/utils.ts:26]: We need to add a few more models in here

**Review by jorgeantonio21 — CHANGES_REQUESTED** [review]

File: utils/utils.ts (hunk 1 above)
Comment (fishonamos) [reply utils/utils.ts:26]: Okay.

File: utils/utils.ts [hunk 2]
```diff
@@ -15,11 +15,35 @@ export async function fetchAvailableModels(): Promise<TaskResponse> {
...
+      return "Llama 3.1 8B";
+    case "Infermatic/Llama-3.3-70B-Instruct-FP8-Dynamic":
+      return "Llama 3.3 70B";
```
Comment (jorgeantonio21) [inline utils/utils.ts]: `Llama3.3` and not `Llama 3.3`

File: utils/utils.ts [hunk 3]
```diff
@@ -15,11 +15,35 @@ export async function fetchAvailableModels(): Promise<TaskResponse> {
...
+export function readableModelName(modelName: string) {
+  switch (modelName) {
+    case "Qwen/QwQ-32B":
+      return "QWQ 32B";
+    case "neuralmagic/DeepSeek-R1-Distill-Llama-70B-FP8-dynamic":
+      return "DeepSeek: R1 Distill Llama 70B";
+    case "neuralmagic/Qwen2-72B-Instruct-FP8":
+      return "Qwen2 72B";
+    case "meta-llama/Llama-3.1-8B-Instruct":
+      return "Llama 3.1 8B";
```
Comment (jorgeantonio21) [inline utils/utils.ts]: Same in here

**Review by jorgeantonio21 — CHANGES_REQUESTED** [review]
Fix conflicts

**Review by jorgeantonio21 — APPROVED** [review]
