### PR TITLE
fix: major UI update to new version

### LINKED ISSUE #13: Review and Merge Style Change PR from Marcus

### PR DESCRIPTION
**Pull request by fishonamos**
Closes #13 #17

- [x] Major update UI to new style
- [x] Update playground
- [x] Add refresh on logout and login points

### CODE REVIEW

File: components/analytics/usage-history.tsx [hunk 1]
```diff
@@ -102,39 +94,33 @@ export function UsageHistory() {
...
     })();
-  }, [settings.loggedIn]);
+  }, []);
   return (
     <Card>
       <CardHeader>
         <CardTitle className="text-sm font-medium">Usage History</CardTitle>
       </CardHeader>
       <CardContent>
-        {usageHistory ? (
```
Comment (Cifko) [inline components/analytics/usage-history.tsx:112]: Don't delete the changes I made. They show Loading when the usage history is being loaded (showing `LoadingCircle` component)

File: components/analytics/usage-history.tsx [hunk 2]
```diff
@@ -67,22 +65,16 @@ interface IUsageHistory {
...
   useEffect(() => {
-    if (!settings.loggedIn) {
-      setUsageHistory([]);
-      return;
-    }
-    setUsageHistory(null);
     (async () => {
       let stacksPromise = await getAllStacks().catch(ex => {
-        showToast("Error occurred", "error");
+        showToast("Error Occured", "error");
```
Comment (Cifko) [inline components/analytics/usage-history.tsx:73]: it's spelled `occurred` if you want to just capitalized the first letter of it to `Occurred` I don't mind.

File: app/layout.tsx [hunk 3]
```diff
@@ -26,26 +26,24 @@ export default function RootLayout({ children }: { children: React.ReactNode })
     <html lang="en" suppressHydrationWarning>
       <body className={inter.className}>
         <SettingsProvider>
-          <AppStateProvider>
```
Comment (Cifko) [inline app/layout.tsx:29]: Keep the `AppStateProvider` I've added that to share application state. Similar to SettingsProvider, but it's not stored in LocalStorage

File: components/AuthForm.tsx [hunk 4]
```diff
@@ -18,7 +18,7 @@ const AuthForm: React.FC<AuthFormProps> = ({ type, onClose }) => {
   const [isLoading, setIsLoading] = useState<boolean>(false);
   const toastRef = useRef<Toast>(null);
   const { settings, updateSettings, updateZkLoginSettings } = useSettings();
-
+  const router = useRouter();
```
Comment (Cifko) [inline components/AuthForm.tsx:21]: you've added this, but I don't see it being used.

File: components/AuthForm.tsx [hunk 5]
```diff
@@ -41,7 +41,8 @@ const AuthForm: React.FC<AuthFormProps> = ({ type, onClose }) => {
         life: 3000,
       });
       //onClose();
-      window.location.reload();
+
+      window.location.href = "/";
```
Comment (Cifko) [inline components/AuthForm.tsx:45]: This will cause to go to Networks Status, instead of staying at the same page (e.g. Account Portal)

File: components/credit-balance-card.tsx [hunk 6]
```diff
@@ -47,9 +45,10 @@ export function CreditBalanceCard({ handleAddFunds }: { handleAddFunds: () => vo
         </div>
         <Button
           className="w-full bg-primary hover:bg-secondary-foreground text-base"
-          onClick={() => (loggedIn ? handleAddFunds : updateState({ showLogin: true }))}
+          disabled={!loggedIn}
+          onClick={handleAddFunds}
```
Comment (Cifko) [inline components/credit-balance-card.tsx:49]: Looks like this whole file was not rebased, just forced pushed.
Revert all changes in this file.

File: components/sidebar.tsx [hunk 7]
```diff
@@ -23,15 +23,11 @@ import { useSettings } from "@/contexts/settings-context";
 
 const navigation = [
   { name: "Network Status", href: "/", icon: Network },
-  { name: "Account Portal", href: "/account-portal", icon: LayoutDashboard },
+  { name: "Account Portal", href: "/account-portal", icon: LayoutDashboard, needAuth: true },
```
Comment (Cifko) [inline components/sidebar.tsx:26]: Don't put this back, we agreed 2 days ago, we will show this and that we will show login button instead of Add Funds on the account portal.

File: components/sidebar.tsx [hunk 8]
```diff
@@ -161,6 +160,9 @@ export function Sidebar() {
           <div className="flex-1 overflow-auto dark:bg-darkMode">
             <nav className="flex-1 space-y-2 px-2 py-4 dark:text-[#8f8f98]">
               {navigation.map(item => {
+                if (item.needAuth && !settings.loggedIn) {
```
Comment (Cifko) [inline components/sidebar.tsx:163]: Remove this, we will not filter the menu based on login.

File: components/top-nav.tsx [hunk 9]
```diff
@@ -18,24 +18,22 @@ import { ThemeToggle } from "@/components/ui/theme-toggle";
 import AuthForm from "@/components/AuthForm";
 import Modal from "@/components/Modal";
 import { getUserProfile } from "@/lib/api";
-import { useAppState } from "@/contexts/app-state";
```
Comment (Cifko) [inline components/top-nav.tsx:21]: revert

File: components/top-nav.tsx [hunk 10]
```diff
@@ -18,24 +18,22 @@ import { ThemeToggle } from "@/components/ui/theme-toggle";
...
 
 export function TopNav() {
   const pathname = usePathname();
   const [loggedIn, setLoggedIn] = useState(false); // To prevent hydration error on client side
   const { settings, updateSettings, updateZkLoginSettings } = useSettings();
-  const { state, updateState } = useAppState();
```
Comment (Cifko) [inline components/top-nav.tsx:27]: revert

File: components/top-nav.tsx [hunk 11]
```diff
@@ -18,24 +18,22 @@ import { ThemeToggle } from "@/components/ui/theme-toggle";
...
 
   const handleAuth = (type: string) => {
     setAuthType(type);
-    updateState({ showLogin: true });
+    setShowAuthForm(true);
   };
 
   const closeAuthForm = () => {
-    updateState({ showLogin: false });
+    setShowAuthForm(false);
```
Comment (Cifko) [inline components/top-nav.tsx:36]: revert

File: components/top-nav.tsx [hunk 12]
```diff
@@ -18,24 +18,22 @@ import { ThemeToggle } from "@/components/ui/theme-toggle";
...
   const { settings, updateSettings, updateZkLoginSettings } = useSettings();
-  const { state, updateState } = useAppState();
   const [showAuthForm, setShowAuthForm] = useState(false);
   const [authType, setAuthType] = useState("login");
   const [username, setUsername] = useState("user");
 
   const handleAuth = (type: string) => {
     setAuthType(type);
-    updateState({ showLogin: true });
+    setShowAuthForm(true);
```
Comment (Cifko) [inline components/top-nav.tsx:32]: revert

File: contexts/app-state.tsx
Comment (Cifko) [inline contexts/app-state.tsx:1]: don't delete

File: components/top-nav.tsx [hunk 13]
```diff
@@ -114,6 +108,7 @@ export function TopNav() {
                       maxEpoch: undefined,
                       zkp: undefined,
                     });
+                    window.location.href = "/";
```
Comment (Cifko) [inline components/top-nav.tsx:111]: Why do this? That will cause switching the pane that user is currently in.
revert

**Review by Cifko — CHANGES_REQUESTED** [review]

File: components/top-nav.tsx (hunk 13 above)
Comment (fishonamos) [reply components/top-nav.tsx]: Yes. To take the back to home on logout or login.

File: contexts/settings-context.tsx
Comment (Cifko) [inline contexts/settings-context.tsx:1]: revert this file
I've cleaned it, because we don't use that stuff

File: components/AuthForm.tsx [hunk 14]
```diff
@@ -5,7 +5,7 @@ import { InputText } from "primereact/inputtext";
 import ZkLogin from "@/lib/zklogin";
 import { useSettings } from "@/contexts/settings-context";
 import { loginUser, registerUser } from "@/lib/api";
-
+import { useRouter } from "next/navigation";
```
Comment (Cifko) [inline components/AuthForm.tsx:8]: this is not used, remove

File: components/LoadingCircle.tsx
Comment (Cifko) [inline components/LoadingCircle.tsx:1]: revert this file
I've changed it so we can use it elsewhere, the 10em was way too big

**Review by Cifko — CHANGES_REQUESTED** [review]
Better, still some changes required.
But it doesn't close the #15
Does it close the #17? I don't see any changes to playground in this PR.

File: components/LoadingCircle.tsx
Comment (fishonamos) [reply components/LoadingCircle.tsx:1]: we have we can update it to use arrays of diiferent size classes. I think that is better.

Comment (fishonamos) [reply components/LoadingCircle.tsx:1]: Screenshot 2025-03-14 at 14 32 45

File: utils/utils.ts [hunk 15]
```diff
@@ -7,19 +7,20 @@ export function renderModelListBasedOnTabs(
     case "chat":
       return [
         {
-          modelName: "Llama 3.3 70B",
-          model: "meta-llama/Llama-3.3-70B-Instruct",
+          modelName: "QwQ 32B",
```
Comment (Cifko) [inline utils/utils.ts:10]: This needs to pull data from proxy. But can be done in a different PR. Just create github issue for it so we don't forget.

**Review by Cifko — APPROVED** [review]

File: utils/utils.ts (hunk 15 above)
Comment (fishonamos) [reply utils/utils.ts:10]: Yes. I will do that.
